#!/usr/bin/python

#    Copyright (C) 2012-2017 Carl Hetherington <cth@carlh.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

from __future__ import print_function
import os
import sys
import shutil
import glob
import tempfile
import argparse
import datetime
import subprocess
import re
import copy
import inspect

TEMPORARY_DIRECTORY = '/var/tmp'

class Error(Exception):
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return self.value
    def __repr__(self):
        return str(self)

class Trees:
    """
    Store for Tree objects which re-uses already-created objects
    and checks for requests for different versions of the same thing.
    """

    def __init__(self):
        self.trees = []

    def get(self, name, specifier, target):
        for t in self.trees:
            if t.name == name and t.specifier == specifier and t.target == target:
                return t
            elif t.name == name and t.specifier != specifier:
                raise Error('conflicting versions of %s requested (%s and %s)' % (name, specifier, t.specifier))

        nt = Tree(name, specifier, target)
        self.trees.append(nt)
        return nt

class Globals:
    quiet = False
    command = None
    dry_run = False
    trees = Trees()

globals = Globals()


#
# Configuration
#

class Option(object):
    def __init__(self, key, default=None):
        self.key = key
        self.value = default

    def offer(self, key, value):
        if key == self.key:
            self.value = value

class BoolOption(object):
    def __init__(self, key):
        self.key = key
        self.value = False

    def offer(self, key, value):
        if key == self.key:
            self.value = (value == 'yes' or value == '1' or value == 'true')

class Config:
    def __init__(self):
        self.options = [ Option('windows_environment_prefix'),
                         Option('mingw_prefix'),
                         Option('git_prefix'),
                         Option('osx_build_host'),
                         Option('osx_environment_prefix'),
                         Option('osx_sdk_prefix'),
                         Option('osx_sdk'),
                         Option('parallel', 4) ]

        try:
            f = open('%s/.config/cdist' % os.path.expanduser('~'), 'r')
            while True:
                l = f.readline()
                if l == '':
                    break

                if len(l) > 0 and l[0] == '#':
                    continue

                s = l.strip().split()
                if len(s) == 2:
                    for k in self.options:
                        k.offer(s[0], s[1])
        except:
            raise

    def get(self, k):
        for o in self.options:
            if o.key == k:
                if o.value is None:
                    raise Error('Required setting %s not found' % k)
                return o.value

    def set(self, k, v):
        for o in self.options:
            o.offer(k, v)

config = Config()

#
# Utility bits
#

def log(m):
    if not globals.quiet:
        print('\x1b[33m* %s\x1b[0m' % m)

def scp_escape(n):
    """Escape a host:filename string for use with an scp command"""
    s = n.split(':')
    assert(len(s) == 1 or len(s) == 2)
    if len(s) == 2:
        return '%s:"\'%s\'"' % (s[0], s[1])
    else:
        return '\"%s\"' % s[0]

def copytree(a, b):
    log('copy %s -> %s' % (scp_escape(b), scp_escape(b)))
    command('scp -r %s %s' % (scp_escape(a), scp_escape(b)))

def copyfile(a, b):
    log('copy %s -> %s' % (scp_escape(a), scp_escape(b)))
    command('scp %s %s' % (scp_escape(a), scp_escape(b)))

def makedirs(d):
    """
    Make directories either locally or on a remote host; remotely if
    d includes a colon, otherwise locally.
    """
    if d.find(':') == -1:
        os.makedirs(d)
    else:
        s = d.split(':')
        command('ssh %s -- mkdir -p %s' % (s[0], s[1]))

def rmdir(a):
    log('remove %s' % a)
    os.rmdir(a)

def rmtree(a):
    log('remove %s' % a)
    shutil.rmtree(a, ignore_errors=True)

def command(c):
    log(c)
    r = os.system(c)
    if (r >> 8):
        raise Error('command %s failed' % c)

def command_and_read(c):
    log(c)
    p = subprocess.Popen(c.split(), stdout=subprocess.PIPE)
    f = os.fdopen(os.dup(p.stdout.fileno()))
    return f

def read_wscript_variable(directory, variable):
    f = open('%s/wscript' % directory, 'r')
    while True:
        l = f.readline()
        if l == '':
            break

        s = l.split()
        if len(s) == 3 and s[0] == variable:
            f.close()
            return s[2][1:-1]

    f.close()
    return None

def set_version_in_wscript(version):
    f = open('wscript', 'rw')
    o = open('wscript.tmp', 'w')
    while True:
        l = f.readline()
        if l == '':
            break

        s = l.split()
        if len(s) == 3 and s[0] == "VERSION":
            print("Writing %s" % version)
            print("VERSION = '%s'" % version, file=o)
        else:
            print(l, file=o, end="")
    f.close()
    o.close()

    os.rename('wscript.tmp', 'wscript')

def append_version_to_changelog(version):
    try:
        f = open('ChangeLog', 'r')
    except:
        log('Could not open ChangeLog')
        return

    c = f.read()
    f.close()

    f = open('ChangeLog', 'w')
    now = datetime.datetime.now()
    f.write('%d-%02d-%02d  Carl Hetherington  <cth@carlh.net>\n\n\t* Version %s released.\n\n' % (now.year, now.month, now.day, version))
    f.write(c)

def append_version_to_debian_changelog(version):
    if not os.path.exists('debian'):
        log('Could not find debian directory')
        return

    command('dch -b -v %s-1 "New upstream release."' % version)

def devel_to_git(git_commit, filename):
    if git_commit is not None:
        filename = filename.replace('devel', '-%s' % git_commit)
    return filename

class TreeDirectory:
    def __init__(self, tree):
        self.tree = tree
    def __enter__(self):
        self.cwd = os.getcwd()
        os.chdir('%s/src/%s' % (self.tree.target.directory, self.tree.name))
    def __exit__(self, type, value, traceback):
        os.chdir(self.cwd)

#
# Version
#

class Version:
    def __init__(self, s):
        self.devel = False

        if s.startswith("'"):
            s = s[1:]
        if s.endswith("'"):
            s = s[0:-1]

        if s.endswith('devel'):
            s = s[0:-5]
            self.devel = True

        if s.endswith('pre'):
            s = s[0:-3]

        p = s.split('.')
        self.major = int(p[0])
        self.minor = int(p[1])
        if len(p) == 3:
            self.micro = int(p[2])
        else:
            self.micro = 0

    def bump_minor(self):
        self.minor += 1
        self.micro = 0

    def bump_micro(self):
        self.micro += 1

    def to_devel(self):
        self.devel = True

    def to_release(self):
        self.devel = False

    def __str__(self):
        s = '%d.%d.%d' % (self.major, self.minor, self.micro)
        if self.devel:
            s += 'devel'

        return s

#
# Targets
#

class Target(object):
    """
    Class representing the target that we are building for.  This is exposed to cscripts,
    though not all of it is guaranteed 'API'.  cscripts may expect:

    platform: platform string (e.g. 'windows', 'linux', 'osx')
    parallel: number of parallel jobs to run
    directory: directory to work in
    variables: dict of environment variables
    debug: True to build a debug version, otherwise False
    set(a, b): set the value of variable 'a' to 'b'
    unset(a): unset the value of variable 'a'
    command(c): run the command 'c' in the build environment

    """

    def __init__(self, platform, directory=None):
        """
        platform -- platform string (e.g. 'windows', 'linux', 'osx')
        directory -- directory to work in; if None we will use a temporary directory
        Temporary directories will be removed after use; specified directories will not.
        """
        self.platform = platform
        self.parallel = int(config.get('parallel'))

        # self.directory is the working directory
        if directory is None:
            self.directory = tempfile.mkdtemp('', 'tmp', TEMPORARY_DIRECTORY)
            self.rmdir = True
        else:
            self.directory = directory
            self.rmdir = False

        # Environment variables that we will use when we call cscripts
        self.variables = {}
        self.debug = False

    def package(self, project, checkout, output_dir):
        tree = globals.trees.get(project, checkout, self)
        tree.build_dependencies()
        tree.build()
        for p in tree.call('package', tree.version):
            copyfile(p, os.path.join(output_dir, os.path.basename(devel_to_git(tree.git_commit, p))))

    def test(self, tree, test):
        """test is the test case to run, or None"""
        tree.build_dependencies()
        tree.build()
        return tree.call('test', test)

    def set(self, a, b):
        self.variables[a] = b

    def unset(self, a):
        del(self.variables[a])

    def get(self, a):
        return self.variables[a]

    def append_with_space(self, k, v):
        if (not k in self.variables) or len(self.variables[k]) == 0:
            self.variables[k] = '"%s"' % v
        else:
            e = self.variables[k]
            if e[0] == '"' and e[-1] == '"':
                self.variables[k] = '"%s %s"' % (e[1:-1], v)
            else:
                self.variables[k] = '"%s %s"' % (e, v)

    def variables_string(self, escaped_quotes=False):
        e = ''
        for k, v in self.variables.items():
            if escaped_quotes:
                v = v.replace('"', '\\"')
            e += '%s=%s ' % (k, v)
        return e

    def cleanup(self):
        if self.rmdir:
            rmtree(self.directory)


class WindowsTarget(Target):
    """
    This target exposes the following additional API:

    version: Windows version ('xp' or None)
    bits: bitness of Windows (32 or 64)
    environment_prefix: path to Windows environment
    mingw_path: path to mingw binaries
    """
    def __init__(self, version, bits, directory=None):
        super(WindowsTarget, self).__init__('windows', directory)
        self.version = version
        self.bits = bits

        self.environment_prefix = '%s/%d' % (config.get('windows_environment_prefix'), self.bits)
        if not os.path.exists(self.environment_prefix):
            raise Error('environment prefix %s does not exist' % self.environment_prefix)

        if self.bits == 32:
            self.mingw_name = 'i686'
        else:
            self.mingw_name = 'x86_64'

        self.mingw_path = '%s/%d/bin' % (config.get('mingw_prefix'), self.bits)
        self.mingw_prefixes = ['/%s/%d' % (config.get('mingw_prefix'), self.bits), '%s/%d/%s-w64-mingw32' % (config.get('mingw_prefix'), bits, self.mingw_name)]

        self.set('PKG_CONFIG_LIBDIR', '%s/lib/pkgconfig' % self.environment_prefix)
        self.set('PKG_CONFIG_PATH', '%s/lib/pkgconfig:%s/bin/pkgconfig' % (self.directory, self.directory))
        self.set('PATH', '%s/bin:%s:%s' % (self.environment_prefix, self.mingw_path, os.environ['PATH']))
        self.set('CC', '%s-w64-mingw32-gcc' % self.mingw_name)
        self.set('CXX', '%s-w64-mingw32-g++' % self.mingw_name)
        self.set('LD', '%s-w64-mingw32-ld' % self.mingw_name)
        self.set('RANLIB', '%s-w64-mingw32-ranlib' % self.mingw_name)
        self.set('WINRC', '%s-w64-mingw32-windres' % self.mingw_name)
        cxx = '-I%s/include -I%s/include' % (self.environment_prefix, self.directory)
        link = '-L%s/lib -L%s/lib' % (self.environment_prefix, self.directory)
        for p in self.mingw_prefixes:
            cxx += ' -I%s/include' % p
            link += ' -L%s/lib' % p
        self.set('CXXFLAGS', '"%s"' % cxx)
        self.set('CPPFLAGS', '')
        self.set('LINKFLAGS', '"%s"' % link)
        self.set('LDFLAGS', '"%s"' % link)

        # This is for backwards-compatibility
        self.windows_prefix = self.environment_prefix

    def command(self, c):
        log('host -> %s' % c)
        command('%s %s' % (self.variables_string(), c))

class LinuxTarget(Target):
    """
    Build for Linux in a docker container.
    This target exposes the following additional API:

    distro: distribution ('debian', 'ubuntu', 'centos' or 'fedora')
    version: distribution version (e.g. '12.04', '8', '6.5')
    bits: bitness of the distribution (32 or 64)
    """

    def __init__(self, distro, version, bits, directory=None):
        super(LinuxTarget, self).__init__('linux', directory)
        self.distro = distro
        self.version = version
        self.bits = bits

        self.set('CXXFLAGS', '-I%s/include' % self.directory)
        self.set('CPPFLAGS', '')
        self.set('LINKFLAGS', '-L%s/lib' % self.directory)
        self.set('PKG_CONFIG_PATH',
                 '%s/lib/pkgconfig:%s/lib64/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig' % (self.directory, self.directory))
        self.set('PATH', '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin')

class DockerTarget(LinuxTarget):
    """Build in a docker container"""
    def __init__(self, distro, version, bits, directory=None):
        super(DockerTarget, self).__init__(distro, version, bits, directory)

    def package(self, project, checkout, output_dir):
        ch = ''
        if checkout is not None:
            ch = '-c %s' % checkout
        target = '%s-%s-%s' % (self.distro, self.version, self.bits)
        container = command_and_read('docker run -itd %s /bin/bash' % target).read().strip()
        command('docker exec -t %s /bin/bash -c "cdist -p %s -t %s -d %s package -w /cdist"' % (container, project, target, ch))
        # I can't get wildcards to work with docker cp
        debs = command_and_read('docker exec -t %s ls -1 /%s' % (container, target)).read().split('\n')
        for d in debs:
            d = d.strip()
            if len(d) > 0:
                command('docker cp %s:/%s/%s %s' % (container, target, d, output_dir))
        command('docker kill %s' % container)

class DirectTarget(LinuxTarget):
    """Build directly in the current environment"""
    def __init__(self, distro, version, bits, directory=None):
        super(DirectTarget, self).__init__(distro, version, bits, directory)

    def command(self, c):
        command('%s %s' % (self.variables_string(), c))


class OSXTarget(Target):
    def __init__(self, directory=None):
        super(OSXTarget, self).__init__('osx', directory)
        self.sdk = config.get('osx_sdk')
        self.sdk_prefix = config.get('osx_sdk_prefix')
        self.environment_prefix = config.get('osx_environment_prefix')

    def command(self, c):
        command('%s %s' % (self.variables_string(False), c))


class OSXSingleTarget(OSXTarget):
    def __init__(self, bits, directory=None):
        super(OSXSingleTarget, self).__init__(directory)
        self.bits = bits

        if bits == 32:
            arch = 'i386'
        else:
            arch = 'x86_64'

        flags = '-isysroot %s/MacOSX%s.sdk -arch %s' % (self.sdk_prefix, self.sdk, arch)
        enviro = '%s/%d' % (config.get('osx_environment_prefix'), bits)

        # Environment variables
        self.set('CFLAGS', '"-I%s/include -I%s/include %s"' % (self.directory, enviro, flags))
        self.set('CPPFLAGS', '')
        self.set('CXXFLAGS', '"-I%s/include -I%s/include %s"' % (self.directory, enviro, flags))
        self.set('LDFLAGS', '"-L%s/lib -L%s/lib %s"' % (self.directory, enviro, flags))
        self.set('LINKFLAGS', '"-L%s/lib -L%s/lib %s"' % (self.directory, enviro, flags))
        self.set('PKG_CONFIG_PATH', '%s/lib/pkgconfig:%s/lib/pkgconfig:/usr/lib/pkgconfig' % (self.directory, enviro))
        self.set('PATH', '$PATH:/usr/bin:/sbin:/usr/local/bin:%s/bin' % enviro)
        self.set('MACOSX_DEPLOYMENT_TARGET', config.get('osx_sdk'))

    def package(self, project, checkout, output_dir):
        raise Error('cannot package non-universal OS X versions')


class OSXUniversalTarget(OSXTarget):
    def __init__(self, directory=None):
        super(OSXUniversalTarget, self).__init__(directory)

    def package(self, project, checkout, output_dir):

        for b in [32, 64]:
            target = OSXSingleTarget(b, os.path.join(self.directory, '%d' % b))
            tree = globals.trees.get(project, checkout, target)
            tree.build_dependencies()
            tree.build()

        tree = globals.trees.get(project, checkout, self)
        with TreeDirectory(tree):
            for p in tree.call('package', tree.version):
                copyfile(p, os.path.join(output_dir, os.path.basename(devel_to_git(tree.git_commit, p))))

class SourceTarget(Target):
    """Build a source .tar.bz2"""
    def __init__(self):
        super(SourceTarget, self).__init__('source')

    def command(self, c):
        log('host -> %s' % c)
        command('%s %s' % (self.variables_string(), c))

    def cleanup(self):
        rmtree(self.directory)

    def package(self, project, checkout, output_dir):
        tree = globals.trees.get(project, checkout, self)
        with TreeDirectory(tree):
            name = read_wscript_variable(os.getcwd(), 'APPNAME')
            command('./waf dist')
            p = os.path.abspath('%s-%s.tar.bz2' % (name, tree.version))
            copyfile(p, os.path.join(output_dir, os.path.basename(devel_to_git(tree.git_commit, p))))

# @param s Target string:
#       windows-{32,64}
#    or ubuntu-version-{32,64}
#    or debian-version-{32,64}
#    or centos-version-{32,64}
#    or fedora-version-{32,64}
#    or osx-{32,64}
#    or source
# @param debug True to build with debugging symbols (where possible)
def target_factory(s, direct, debug, work):
    target = None
    if s.startswith('windows-'):
        x = s.split('-')
        if len(x) == 2:
            target = WindowsTarget(None, int(x[1]), work)
        elif len(x) == 3:
            target = WindowsTarget(x[1], int(x[2]), work)
        else:
            raise Error("Bad Windows target name `%s'")
    elif s.startswith('ubuntu-') or s.startswith('debian-') or s.startswith('centos-') or s.startswith('fedora'):
        p = s.split('-')
        if len(p) != 3:
            raise Error("Bad Linux target name `%s'; must be something like ubuntu-12.04-32 (i.e. distro-version-bits)" % s)
        if direct:
            target = DirectTarget(p[0], p[1], int(p[2]), work)
        else:
            target = DockerTarget(p[0], p[1], int(p[2]), work)
    elif s.startswith('arch-'):
        p = s.split('-')
        if len(p) != 2:
            raise Error("Bad Arch target name `%s'; must be arch-32 or arch-64")
        target = DockerTarget(p[0], None, p[1], work)
    elif s == 'raspbian':
        target = DockerTarget(s, None, None, work)
    elif s.startswith('osx-'):
        target = OSXSingleTarget(int(s.split('-')[1]), work)
    elif s == 'osx':
        if globals.command == 'build':
            target = OSXSingleTarget(64, work)
        else:
            target = OSXUniversalTarget(work)
    elif s == 'source':
        target = SourceTarget()
    elif s == 'docker':
        target = DockerTarget()

    if target is None:
        raise Error("Bad target `%s'" % s)

    target.debug = debug
    return target


#
# Tree
#

class Tree(object):
    """Description of a tree, which is a checkout of a project,
       possibly built.  This class is never exposed to cscripts.
       Attributes:
           name -- name of git repository (without the .git)
           specifier -- git tag or revision to use
           target --- target object that we are using
           version --- version from the wscript (if one is present)
           git_commit -- git revision that is actually being used
           built --- true if the tree has been built yet in this run
    """

    def __init__(self, name, specifier, target):
        self.name = name
        self.specifier = specifier
        self.target = target
        self.version = None
        self.git_commit = None
        self.built = False

        cwd = os.getcwd()

        flags = ''
        redirect = ''
        if globals.quiet:
            flags = '-q'
            redirect = '>/dev/null'
        command('git clone %s %s/%s.git %s/src/%s' % (flags, config.get('git_prefix'), self.name, target.directory, self.name))
        os.chdir('%s/src/%s' % (target.directory, self.name))

        spec = self.specifier
        if spec is None:
            spec = 'master'

        command('git checkout %s %s %s' % (flags, spec, redirect))
        self.git_commit = command_and_read('git rev-parse --short=7 HEAD').readline().strip()
        command('git submodule init --quiet')
        command('git submodule update --quiet')

        proj = '%s/src/%s' % (target.directory, self.name)

        self.cscript = {}
        exec(open('%s/cscript' % proj).read(), self.cscript)

        if os.path.exists('%s/wscript' % proj):
            v = read_wscript_variable(proj, "VERSION");
            if v is not None:
                self.version = Version(v)

        os.chdir(cwd)

    def call(self, function, *args):
        with TreeDirectory(self):
            return self.cscript[function](self.target, *args)

    def build_dependencies(self, options=None):

        if not 'dependencies' in self.cscript:
            return

        if len(inspect.getargspec(self.cscript['dependencies']).args) == 2:
            deps = self.call('dependencies', options)
        else:
            log("Deprecated cscipt dependencies() method with no parameter")
            deps = self.call('dependencies')

        for d in deps:
            dep = globals.trees.get(d[0], d[1], self.target)

            options = dict()
            # Make the options to pass in from the option_defaults of the thing
            # we are building and any options specified by the parent.
            if 'option_defaults' in dep.cscript:
                for k, v in dep.cscript['option_defaults']().items():
                    options[k] = v

            if len(d) > 2:
                for k, v in d[2].items():
                    options[k] = v

            msg = 'Building dependency %s %s of %s' % (d[0], d[1], self.name)
            if len(options) > 0:
                msg += ' with options %s' % options
            log(msg)

            dep.build_dependencies(options)
            dep.build(options)

    def build(self, options=None):
        if self.built:
            return

        variables = copy.copy(self.target.variables)

        if not globals.dry_run:
            if len(inspect.getargspec(self.cscript['build']).args) == 2:
                self.call('build', options)
            else:
                self.call('build')

        self.target.variables = variables
        self.built = True

#
# Command-line parser
#

def main():

    commands = {
        "build": "build project",
        "package": "package and build project",
        "release": "release a project using its next version number (changing wscript and tagging)",
        "pot": "build the project's .pot files",
        "changelog": "generate a simple HTML changelog",
        "manual": "build the project's manual",
        "doxygen": "build the project's Doxygen documentation",
        "latest": "print out the latest version",
        "test": "run the project's unit tests",
        "shell": "build the project then start a shell",
        "checkout": "check out the project",
        "revision": "print the head git revision number"
    }

    one_of = "Command is one of:\n"
    summary = ""
    for k, v in commands.items():
        one_of += "\t%s\t%s\n" % (k, v)
        summary += k + " "

    parser = argparse.ArgumentParser()
    parser.add_argument('command', help=summary)
    parser.add_argument('-p', '--project', help='project name')
    parser.add_argument('--minor', help='minor version number bump', action='store_true')
    parser.add_argument('--micro', help='micro version number bump', action='store_true')
    parser.add_argument('--major', help='major version to return with latest', type=int)
    parser.add_argument('-c', '--checkout', help='string to pass to git for checkout')
    parser.add_argument('-o', '--output', help='output directory', default='.')
    parser.add_argument('-q', '--quiet', help='be quiet', action='store_true')
    parser.add_argument('-t', '--target', help='target')
    parser.add_argument('-d', '--direct', help='build in the current environment', action='store_true')
    parser.add_argument('-k', '--keep', help='keep working tree', action='store_true')
    parser.add_argument('--debug', help='build with debugging symbols where possible', action='store_true')
    parser.add_argument('-w', '--work', help='override default work directory')
    parser.add_argument('-g', '--git-prefix', help='override configured git prefix')
    parser.add_argument('--test', help='name of test to run (with `test''), defaults to all')
    parser.add_argument('-n', '--dry-run', help='run the process without building anything', action='store_true')
    args = parser.parse_args()

    # Override configured stuff
    if args.git_prefix is not None:
        config.set('git_prefix', args.git_prefix)

    if args.output.find(':') == -1:
        # This isn't of the form host:path so make it absolute
        args.output = os.path.abspath(args.output) + '/'
    else:
        if args.output[-1] != ':' and args.output[-1] != '/':
            args.output += '/'

    # Now, args.output is 'host:', 'host:path/' or 'path/'

    if args.work is not None:
        args.work = os.path.abspath(args.work)

    if args.project is None and args.command != 'shell':
        raise Error('you must specify -p or --project')

    globals.quiet = args.quiet
    globals.command = args.command
    globals.dry_run = args.dry_run

    if not globals.command in commands:
        e = 'command must be one of:\n' + one_of
        raise Error('command must be one of:\n%s' % one_of)

    if globals.command == 'build':
        if args.target is None:
            raise Error('you must specify -t or --target')

        target = target_factory(args.target, args.direct, args.debug, args.work)
        tree = globals.trees.get(args.project, args.checkout, target)
        tree.build_dependencies()
        tree.build()
        if not args.keep:
            target.cleanup()

    elif globals.command == 'package':
        if args.target is None:
            raise Error('you must specify -t or --target')

        target = target_factory(args.target, args.direct, args.debug, args.work)

        if target.platform == 'linux':
            output_dir = os.path.join(args.output, '%s-%s-%d' % (target.distro, target.version, target.bits))
        else:
            output_dir = args.output

        makedirs(output_dir)
        target.package(args.project, args.checkout, output_dir)

        if not args.keep:
            target.cleanup()

    elif globals.command == 'release':
        if args.minor is False and args.micro is False:
            raise Error('you must specify --minor or --micro')

        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)

        version = tree.version
        version.to_release()
        if args.minor:
            version.bump_minor()
        else:
            version.bump_micro()

        set_version_in_wscript(version)
        append_version_to_changelog(version)
        append_version_to_debian_changelog(version)

        command('git commit -a -m "Bump version"')
        command('git tag -m "v%s" v%s' % (version, version))

        version.to_devel()
        set_version_in_wscript(version)
        command('git commit -a -m "Bump version"')
        command('git push')
        command('git push --tags')

        target.cleanup()

    elif globals.command == 'pot':
        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)

        pots = tree.call('make_pot')
        for p in pots:
            copyfile(p, '%s%s' % (args.output, os.path.basename(p)))

        target.cleanup()

    elif globals.command == 'changelog':
        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)

        with TreeDirectory(tree):
            text = open('ChangeLog', 'r')

        html = tempfile.NamedTemporaryFile()
        versions = 8

        last = None
        changes = []

        while True:
            l = text.readline()
            if l == '':
                break

            if len(l) > 0 and l[0] == "\t":
                s = l.split()
                if len(s) == 4 and s[1] == "Version" and s[3] == "released.":
                    v = Version(s[2])
                    if v.micro == 0:
                        if last is not None and len(changes) > 0:
                            print("<h2>Changes between version %s and %s</h2>" % (s[2], last), file=html)
                            print("<ul>", file=html)
                            for c in changes:
                                print("<li>%s" % c, file=html)
                            print("</ul>", file=html)
                        last = s[2]
                        changes = []
                        versions -= 1
                        if versions < 0:
                            break
                else:
                    c = l.strip()
                    if len(c) > 0:
                        if c[0] == '*':
                            changes.append(c[2:])
                        else:
                            changes[-1] += " " + c

        copyfile(html.file, '%schangelog.html' % args.output)
        html.close()
        target.cleanup()

    elif globals.command == 'manual':
        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)

        outs = tree.call('make_manual')
        for o in outs:
            if os.path.isfile(o):
                copyfile(o, '%s%s' % (args.output, os.path.basename(o)))
            else:
                copytree(o, '%s%s' % (args.output, os.path.basename(o)))

        target.cleanup()

    elif globals.command == 'doxygen':
        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)

        dirs = tree.call('make_doxygen')
        if hasattr(dirs, 'strip') or (not hasattr(dirs, '__getitem__') and not hasattr(dirs, '__iter__')):
            dirs = [dirs]

        for d in dirs:
            copytree(d, args.output)

        target.cleanup()

    elif globals.command == 'latest':
        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)

        with TreeDirectory(tree):
            f = command_and_read('git log --tags --simplify-by-decoration --pretty="%d"')
            latest = None
            while latest is None:
                t = f.readline()
                m = re.compile(".*\((.*)\).*").match(t)
                if m:
                    tags = m.group(1).split(', ')
                    for t in tags:
                        s = t.split()
                        if len(s) > 1:
                            t = s[1]
                        if len(t) > 0 and t[0] == 'v':
                            v = Version(t[1:])
                            if args.major is None or v.major == args.major:
                                latest = v

        print(latest)
        target.cleanup()

    elif globals.command == 'test':
        if args.target is None:
            raise Error('you must specify -t or --target')

        target = None
        try:
            target = target_factory(args.target, args.direct, args.debug, args.work)
            tree = globals.trees.get(args.project, args.checkout, target)
            with TreeDirectory(tree):
                target.test(tree, args.test)
        except Error as e:
            if target is not None:
                target.cleanup()
            raise

        if target is not None:
            target.cleanup()

    elif globals.command == 'shell':
        if args.target is None:
            raise Error('you must specify -t or --target')

        target = target_factory(args.target, args.direct, args.debug, args.work)
        target.command('bash')

    elif globals.command == 'revision':

        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)
        with TreeDirectory(tree):
            print(command_and_read('git rev-parse HEAD').readline().strip()[:7])
        target.cleanup()

    elif globals.command == 'checkout':

        if args.output is None:
            raise Error('you must specify -o or --output')

        target = SourceTarget()
        tree = globals.trees.get(args.project, args.checkout, target)
        with TreeDirectory(tree):
            shutil.copytree('.', args.output)
        target.cleanup()

    else:
        raise Error('invalid command %s' % globals.command)

try:
    main()
except Error as e:
    print('cdist: %s' % str(e), file=sys.stderr)
    sys.exit(1)
