#!/bin/bash

images="ubuntu-16.04-64 ubuntu-18.04-64 ubuntu-20.04-64 ubuntu-22.04-64 ubuntu-24.04-64 ubuntu-25.04-64 ubuntu-25.10-64"
images="$images windows windows_v2.18.x"
images="$images debian-10-64 debian-11-64 debian-12-64 debian-13-64 debian-unstable-64"
images="$images fedora-39-64 fedora-40-64 fedora-41-64 fedora-42-64"
images="$images mageia-8-64 mageia-9-64"
images="$images centos-7-64 centos-stream8-64 centos-stream9-64"
images="$images arch-64 rocky-8-64 rocky-9-64 rocky-10-64"

docker volume rm ccache
docker volume create ccache
volume_id=$(docker run --mount source=ccache,target=/ccache -itd ubuntu-18.04-64 bash)
for user in $USER; do
  id=$(id -u $user)
  for t in $images; do
    docker exec $volume_id mkdir -p /ccache/$t-$id
    docker exec $volume_id chmod 777 /ccache/$t-$id
  done
done
docker kill $volume_id
